### ISSUE TITLE
File blame and diffs not working

### ISSUE THREAD

**Issue by MichalGniadek** [keanemind/jjk#6]
Hi! Thanks for the extension. I'm having some problems though:

1. File blame just doesn't seem to work?
2. File diff doesn't work. When I click on a changed file in the "Parent Revision" foldable in the "Source Control" tab I get a "The editor could not be opened because the file was not found." error. When I click "Try Again" an error message box is displayed:

![Image](https://github.com/user-attachments/assets/27e40e8d-d248-4eac-99ec-37e4b83779a2)

As you can probably tell I'm using Windows (11), not sure if that could be a problem? Let me know if I can get you more info or other help. I will still use this extension for the other nice things that are working!

**Comment by kevin314** [comment]
Thanks for trying out the extension! 

Are you getting the diff issue when you open the diff for any file in source control? Even ones that have only been modified (and not created or deleted)? There was a known issue that caused opening diffs for created/deleted files to result in a similar error to yours, but it's been fixed in the release (v0.5.2) that came out today.

For the file blame problem, could you check if `jj file annotate` works from the command line?

**Comment by MichalGniadek** [comment]
Diff view seems to only work for files added in the current working copy (work as in just opens the file). It doesn't work for files added in the parent commit. And it doesn't work for modified files anywhere.

`jj file annotate` seems to work. Also, while testing, I've noticed that blame works but only in the newly added file opened from the "Source Control > Working Copy" panel. If I just open the same file directly, the blame still doesn't work.

The file tab with working blame has filepath `\\?\C:\Users\Rest\Of\The\Path`. The tab where the blame doesn't work doesn't have the `\\?` at the beginning (the rest of the filepath is the same).

Tested on 0.5.2

**Comment by MichalGniadek** [comment]
Ok, updated the jj version from v0.24 to v0.26 hoping that maybe ["On Windows, workspace paths (printed by jj root) no longer use UNC-style \\?\ paths unless necessary."](https://github.com/jj-vcs/jj/releases/tag/v0.25.0) would help. Well, the blame now works correctly! But I'm still having problems with diffs but with a different error:

![Image](https://github.com/user-attachments/assets/0d4be65a-2a10-4b44-9ee1-e0b271c50018)

And after checking `jj file show C:\Rest\Of'\The\Path`, it does fail in the command line. Passing a relative path to the command works.

Could this extension be changed so that it passes a relative path to the command?

**Comment by keanemind** [comment]
Sorry for the delay. I managed to repro the issue on a Windows machine and think I figured out the root cause. According to the [jj CLI reference](https://jj-vcs.github.io/jj/latest/cli-reference/#jj-file-show), the argument is `<FILESETS>`, not arbitrary paths. The [fileset language](https://jj-vcs.github.io/jj/latest/filesets/) expects either a plain path or `<file pattern>:<path>` where the file pattern is `cwd-file`, `cwd-glob`, etc. Because of the significance of the colon, I think there's a conflict with Windows absolute file paths and other file path formats described [here](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats) where the drive letter is followed by a colon. That would explain why the error is saying `` Invalid file pattern kind `c:` ``. 

I get the same error when I run `jj file show "C:\Absolute\Path\To\File"` as well, and trying to specify the various file patterns before the path, e.g., `jj file show root-file:"C:\Absolute\Path\To\File"`, also results in errors. UNC paths don't seem to work either. Right now I'm thinking the most straightforward way to get around this is to always provide relative paths instead of absolute paths to avoid needing to include the drive letter at all.

**Comment by keanemind** [comment]
This is fixed on my windows machine by https://github.com/keanemind/jjk/commit/6d57db151ad06813edb3883b7d2e38c9a19f9675 which will be included in the next release. Thanks for your patience.

**Comment by kevin314** [comment]
The latest release (0.6.0) should fix this, let us know if the issue persists!

**Comment by MichalGniadek** [comment]
Everything seems to work, thank you!
